eval_kwargs:
  max_tokens: 64
  n: 1
  temperature: 0.0
  top_p: 1.0
  logprobs: 5
eval_method: base_pairwise
instruction_marker: INSTRUCTION
output_marker: OUTPUT
parse_method: base_pairwise
parse_with_tokenizer: false
pattern: Output \((\S+)\)
prompt_method: pairwise_vanilla
sys1_marker: a
sys2_marker: b
