# model configs
max_input_len: 3072
max_model_len: 4096

# eval config
eval_method: 'pairwise_prepair'
prompt_method: 'prepair_aggregation_swap'
instruction_marker: 'INSTRUCTION'
output_marker: 'OUTPUT'

# parse config
sys1_marker: 'a'
sys2_marker: 'b'
parse_method: base_pairwise_cot
parse_with_tokenizer: false
pattern: 'Output \((\S+)\) is better'
eval_kwargs:
  temperature: 0.0
  top_p: 1.0
  n: 1
  max_tokens: 1024
  logprobs: 1
  use_cache: false
  a_then_b: false
  individual_analysis_prompt_dir: 'prompts/prepair_analysis.txt'

fdir_kwargs:
  cache_dir: 'results/cache/{dataset}_{model}/'