eval_kwargs:
  logprobs: 1
  max_tokens: 1024
  n: 9
  temperature: 0.7
  top_p: 0.95
eval_method: base_pairwise
instruction_marker: INSTRUCTION
max_input_len: 3072
max_model_len: 4096
output_marker: OUTPUT
parse_method: base_pairwise_sc
parse_with_tokenizer: false
pattern: Output \((\S+)\) is better
prompt_method: pairwise_cot_swap
sys1_marker: a
sys2_marker: b
file_ext: sc.9
