eval_kwargs:
  num_assistants: 5

eval_method: protocol_vote
parse_method: majority_vote

fdir_kwargs:
  evaluator1_dir: results/{dataset}.{model}.base_pairwise.pairwise_vanilla_swap.jsonl
  evaluator2_dir: results/{dataset}.{model}.base_pairwise.pairwise_cot_swap.jsonl
  evaluator3_dir: results/{dataset}.{model}.base_pairwise_metric.pairwise_metric_swap.jsonl
  evaluator4_dir: results/{dataset}.{model}.base_pairwise_reference.pairwise_reference_swap.jsonl
  evaluator5_dir: results/{dataset}.{model}.base_pairwise_metric_reference.pairwise_metric_reference_swap.jsonl

# dummy parameters, not used
instruction_marker: INSTRUCTION
output_marker: OUTPUT
parse_with_tokenizer: false
pattern: Output \((\S+)\)
prompt_method: majority_vote_swap
sys1_marker: a
sys2_marker: b